[project]
name = "astro-cli-for-orquestration"
version = "0.1.0"
description = "Apache Airflow orchestration project using Astronomer Astro"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
